name: Python

on:
  pull_request:
    paths:
      - "data/**"
      - "python/**"
      - "pyproject.toml"
      - "Makefile"

jobs:
  main:
    runs-on: "ubuntu-latest"
    container:
      image: ${{ matrix.image }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - name: "Fedora Rawhide"
            image: "registry.fedoraproject.org/fedora:rawhide"
          - name: "Fedora Latest"
            image: "registry.fedoraproject.org/fedora:latest"
          - name: "CentOS Stream 10"
            image: "quay.io/centos/centos:stream10-development"
          - name: "CentOS Stream 9"
            image: "quay.io/centos/centos:stream9"

    steps:
      - name: "Checkout the repository"
        uses: actions/checkout@v4

      - name: "Install dependencies"
        run: |
          dnf --setopt install_weak_deps=False install -y python3-pip gpg make
          python3 -m pip install --upgrade pip wheel
          python3 -m pip install .[dev]

      - name: "Use RPM PyYAML on CentOS"
        if: ${{ startsWith(matrix.name, 'CentOS') }}
        run: |
          dnf --setopt install_weak_deps=False install -y python3-pyyaml
          python3 -m pip uninstall -y pyyaml

      - name: "Run static checks"
        if: matrix.name == 'Fedora Rawhide'
        run: |
          make check-py

      - name: "Run tests"
        run: |
          make test-py
